#!/bin/bash

helpme(){
	echo "------------------------------------------------------------"
	echo "| FSEM - Fluka Simulation for Emulsion experiments by ASh  |"
	echo "| This script runs fluka simulation in current directory   |"
	echo "| (it will be used to store temporary FLUKA files)         |"
	echo "| and writes output to given dir                           |"
	echo "------------------------------------------------------------"
  	echo "** usage ** : fsem INPUT_FILE OUTPUT_DIR BEAMFILE_DIR"
  	echo " - INPUT_FILE: FULKA input file (for example BRICK.inp)"
  	echo " - OPTPUT_DIR: Directory for output files"
  	echo " - MIN_ANG: Minimum angle (in mrad) for new track creation       <-- optional, def=0"
  	echo " - BEAMFILE_DIR: Directory with beamfiles (if specified in .inp) <-- optional, def - pwd"
}

fullpath(){
  	echo $(readlink -f $1)
}



if [ "$#" -lt 2 ]; then
	helpme
	exit
fi

echo "Starting FSEM run"

#export FLU_OUT=$2
export FLU_OUT=`fullpath $2`

if [ "$#" -ge 3 ]; then
   export MIN_ANG=$3
else 
   export MIN_ANG=0
fi
      
if [ "$#" -ge 4 ]; then
   export BEAMFILES=`fullpath $3`
else 
   export BEAMFILES=`pwd`
fi
export TXT_OUT=10000
export BIN_OUT=11110

echo "input file= `fullpath $1`"
echo "output dir= $FLU_OUT"
echo "beamfile dir= $BEAMFILES"

$FLUPRO/flutil/rfluka -e $(fullpath $FSEM)/app/bin/FlukaSim -M 1 `fullpath $1` &
sleep 3
watchme="tail -n 3 $FLU_OUT/FluSim.out"
echo "watch this! "$watchme
watch -d $watchme
echo Done!

