#!/bin/bash

helpme(){
	echo "------------------------------------------------------------"
	echo "| FSEM - Fluka Simulation for Emulsion experiments by ASh  |"
	echo "| This script runs fluka simulation in current directory   |"
	echo "| (it will be used to store temporary FLUKA files)         |"
	echo "| and writes output to given dir                           |"
	echo "------------------------------------------------------------"
  	echo "** usage ** : fsem INPUT_FILE OUTPUT_DIR BEAMFILE_DIR"
  	echo " - INPUT_FILE: FULKA input file (for example BRICK.inp)"
  	echo " - OPTPUT_DIR: Directory for output files"
  	echo " - MIN_ANG: Minimum angle (in mrad) for new track creation       <-- optional, def=0"
  	echo " - BEAMFILE_DIR: Directory with beamfiles (if specified in .inp) <-- optional, def - pwd"
}

fullpath(){
  	echo $(readlink -f $1)
}



if [ "$#" -lt 2 ]; then
	helpme
	exit
fi

echo "Starting FSEM run [$1 ; $2]"
echo `fullpath $2`
#export FLU_OUT=$2
export FLU_OUT=`fullpath $2`

if [ "$#" -ge 3 ]; then
   export MIN_ANG=$3
else 
   export MIN_ANG=0
fi
      
if [ "$#" -ge 4 ]; then
   export BEAMFILES=`fullpath $3`
else 
   export BEAMFILES=`pwd`
fi
export TXT_OUT=10000
export BIN_OUT=11110

INPFILE=`fullpath $1`
THISDIF=$PWD
echo "input file= $INPFILE"
echo "output dir= $FLU_OUT"
echo "beamfile dir= $BEAMFILES"
#check if directory exists
if [ ! -d "$FLU_OUT" ]; then
  read -r -p "The directory $FLU_OUT doesn't exist. Do you want to create it? [y/N]" response
    if [[ $response =~ ^([yY])$ ]]
    then
        echo "Create dir $FLU_OUT"
        mkdir $FLU_OUT
    else
        echo "Aborting..."
        exit
    fi
fi
#check if directory is empty
if test "$(ls -A "$FLU_OUT")"; then
  read -r -p "The directory $FLU_OUT is not empty. Do you want to clear it? [y/N]" response
    if [[ $response =~ ^([yY])$ ]]
    then
        echo "Clearing $FLU_OUT"
        rm -rf $FLU_OUT/*
    else
        echo "Leave it as it is..."
    fi
fi
#cd $FLU_OUT; 
$FLUPRO/flutil/rfluka -e $(fullpath $FSEM)/app/bin/FlukaSim -M 1 $INPFILE &
cp $INPFILE $FLU_OUT 
#cd $THISDIR
sleep 3
watchme="tail -n 3 $FLU_OUT/FluSim.out"
echo "watch this! "$watchme
watch -d $watchme
echo Done!

